hanwha-be09-4vengers/Yoribogo

db_queries/public_recipe_script.py
---
name: 기능 수정 이슈
about: 데이터베이스 id, 비번 yoribogo로 변경
title: 'Refactor: 데이터베이스 id, 비번 yoribogo로 변경'
assignees: ''
---
- 
- 
```Python
DATABASE_URL = 'mysql+mysqldb://yoribogo:yoribogo@localhost/yoribogodb'
```
close #
=> Refactor: 데이터베이스 id, 비번 yoribogo로 변경

server/src/main/java/com/avengers/yoribogo/recipe/controller/RecipeController.java, server/src/main/java/com/avengers/yoribogo/recipe/domain/Recipe.java, server/src/main/java/com/avengers/yoribogo/recipe/dto/RecipeDTO.java, server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeService.java, server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java, server/src/test/java/com/avengers/yoribogo/recipe/service/RecipeServiceTests.java
---
name: 기능 개발 이슈
about: 요리 레시피 단건 조회 구현
title: 요리 레시피 단건 조회 구현
---
- 
- 
```Java
// 요리 레시피 단건 조회
@Override
public RecipeDTO findRecipeByRecipeId(Long recipeId) {
// 레시피 조회
Recipe recipe = recipeRepository.findById(recipeId)
.orElseThrow(() -> new CommonException(ErrorCode.NOT_FOUND_RECIPE));
return modelMapper.map(recipe, RecipeDTO.class);
}
```
```Java
@DisplayName("요리 레시피 단건 조회")
@Test
void testFindRecipeByRecipeId() {
// Given
Long recipeId = 1L;
// When
RecipeDTO recipeDTO = recipeService.findRecipeByRecipeId(recipeId);
// Then
Assertions.assertNotNull(recipeDTO, "레시피가 null 입니다.");
// 요소를 로그로 찍기
log.info(recipeDTO.toString());
}
```
- 
close #7
=> Feat: 요리 레시피 단건 조회 구현

server/src/main/java/com/avengers/yoribogo/recipe/controller/RecipeController.java, server/src/main/java/com/avengers/yoribogo/recipe/repository/RecipeRepository.java, server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeService.java, server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java, server/src/test/java/com/avengers/yoribogo/recipe/service/RecipeServiceTests.java
---
name: 기능 개발 이슈
about: 요리 레시피 요리 이름으로 조회 구현
title: Feat: 요리 레시피 요리 이름으로 조회 구현
---
- 
- 
- 최신순으로 정렬(recipeId 기준 역순)
```Java
// 요리 레시피 요리 이름으로 조회
@Override
public Page<RecipeDTO> findRecipeByMenuName(String menuName, Integer pageNo) {
// 페이지 번호 유효성 검사
if (pageNo == null || pageNo < 1) {
throw new CommonException(ErrorCode.INVALID_PARAMETER_FORMAT);
}
// 페이지와 한 페이지당 요소 수 설정 (pageNumber는 0부터 시작)
Pageable pageable = PageRequest.of(
pageNo - 1,
ELEMENTS_PER_PAGE,
Sort.by(Sort.Direction.DESC, "recipeId")
);
// 레시피 조회
Page<Recipe> recipePage = recipeRepository.findByMenuNameContaining(menuName, pageable);
// 레시피가 존재하지 않는 경우
if (recipePage.getContent().isEmpty()) {
throw new CommonException(ErrorCode.NOT_FOUND_RECIPE);
}
// Recipe -> RecipeDTO 변환 …
```
=> Feat: 요리 레시피 요리 이름으로 조회 구현

server/src/main/java/com/avengers/yoribogo/recipe/controller/RecipeController.java, server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeService.java, server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java, server/src/test/java/com/avengers/yoribogo/recipe/service/RecipeServiceTests.java
---
name: 기능 개발 이슈
about: 요리 레시피 수정 구현
title: Feat: 요리 레시피 수정 구현
---
- 
- 
```Java
@Override
public RecipeDTO modifyRecipe(RecipeDTO modifyRecipeDTO) {
// 관리자 여부 확인하는 로직 추가 예정
// 기존 엔티티 조회
Recipe existingRecipe = recipeRepository.findById(modifyRecipeDTO.getRecipeId())
.orElseThrow(() -> new CommonException(ErrorCode.NOT_FOUND_RECIPE));
// 엔티티 정보 수정
existingRecipe.setMenuName(modifyRecipeDTO.getMenuName());
existingRecipe.setMenuImage(modifyRecipeDTO.getMenuImage());
existingRecipe.setMenuIngredient(modifyRecipeDTO.getMenuIngredient());
existingRecipe.setUserId(modifyRecipeDTO.getUserId());
return modelMapper.map(recipeRepository.save(existingRecipe), RecipeDTO.class);
}
```
```Java
@DisplayName("요리 레시피 수정 테스트")
@Test
void testModifyRecipe() {
// …
```
=> Feat: 요리 레시피 수정 구현

db_queries/integrated_data_insert.sql, server/src/main/java/com/avengers/yoribogo/recipe/controller/RecipeController.java, server/src/main/java/com/avengers/yoribogo/recipe/domain/AIRecipe.java, server/src/main/java/com/avengers/yoribogo/recipe/domain/PublicDataRecipe.java, server/src/main/java/com/avengers/yoribogo/recipe/dto/AIRecipeDTO.java, server/src/main/java/com/avengers/yoribogo/recipe/dto/PublicDataRecipeDTO.java, server/src/main/java/com/avengers/yoribogo/recipe/repository/AIRecipeRepository.java, server/src/main/java/com/avengers/yoribogo/recipe/repository/PublicDataRecipeRepository.java, server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeService.java, server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java, server/src/test/java/com/avengers/yoribogo/recipe/service/RecipeServiceTests.java
---
name: 기능 개발 이슈
about: 요리 레시피 등록 구현
title: Feat: 요리 레시피 등록 구현
---
- 
- 
```Java
// 요리 레시피 등록
@Override
public RecipeDTO registRecipe(RecipeDTO registRecipeDTO) {
// 요리 레시피 테이블에 저장
Recipe newRecipe = modelMapper.map(registRecipeDTO, Recipe.class);
newRecipe = recipeRepository.save(newRecipe);
// 요리 구분 검사
if (registRecipeDTO.getMenuType() == MenuType.PUBLIC) {
// DTO에 요리 레시피 정보 담기
PublicDataRecipeDTO publicDataRecipeDTO = PublicDataRecipeDTO
.builder()
.publicDataMenuName(newRecipe.getMenuName())
.publicDataMenuIngredient(newRecipe.getMenuIngredient())
.publicDataMenuImage(newRecipe.getMenuImage())
.recipeId(newRecipe.getRecipeId())
.build();
// 공공데이터 요리 레시피 테이블에 저장
PublicDataRecipe publicDataRecipe =
modelMapper.map(publicDataRecipeDTO, …
```
=> Feat: 요리 레시피 등록 구현

server/src/main/java/com/avengers/yoribogo/recipe/controller/RecommendedMenuController.java, server/src/main/java/com/avengers/yoribogo/recipe/domain/RecommendedMenu.java, server/src/main/java/com/avengers/yoribogo/recipe/domain/RecommendedMenuStatus.java, server/src/main/java/com/avengers/yoribogo/recipe/domain/Satisfaction.java, server/src/main/java/com/avengers/yoribogo/recipe/dto/GoodMenuDTO.java, server/src/main/java/com/avengers/yoribogo/recipe/dto/RecommendedMenuDTO.java, server/src/main/java/com/avengers/yoribogo/recipe/repository/RecommendedMenuRepository.java, server/src/main/java/com/avengers/yoribogo/recipe/service/AIRecipeService.java, server/src/main/java/com/avengers/yoribogo/recipe/service/AIRecipeServiceImpl.java, server/src/main/java/com/avengers/yoribogo/recipe/service/PublicDataRecipeService.java, server/src/main/java/com/avengers/yoribogo/recipe/service/PublicDataRecipeServiceImpl.java, server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java, server/src/main/java/com/avengers/yoribogo/recipe/service/RecommendedMenuService.java, server/src/main/java/com/avengers/yoribogo/recipe/service/RecommendedMenuServiceImpl.java, server/src/test/java/com/avengers/yoribogo/recipe/service/RecommendedMenuServiceTests.java
---
name: 기능 개발 이슈
about: 추천 요리 회원별 조회
title: Feat: 추천 요리 회원별 조회
---
- 
- 
- JPQL
서비스
```Java
// 추천 요리 회원별 조회
@Override
public List<GoodMenuDTO> findRecommendedMenuByUserId(Long userId) {
// 기존 엔티티 목록 조회
List<GoodMenuDTO> recommendedMenuList = recommendedMenuRepository.findRecommendedMenuWithRecipeByUserId(
userId, Satisfaction.GOOD, RecommendedMenuStatus.ACTIVE);
// 조회된 결과가 없을 때 예외 처리
if (recommendedMenuList.isEmpty()) {
throw new CommonException(ErrorCode.NOT_FOUND_RECOMMENDED_MENU);
}
return recommendedMenuList;
}
```
레포지토리
```Java
public interface RecommendedMenuRepository extends JpaRepository<RecommendedMenu, Long> {
// 추천 요리 회원별 조회
@Query("SELECT new com.avengers.yoribogo.recipe.dto.GoodMenuDTO(rm, r) " +
"FROM RecommendedMenu rm " +
"JOIN …
```
=> Feat: 추천 요리 회원별 조회

server/src/main/java/com/avengers/yoribogo/recipe/controller/RecipeController.java, server/src/main/java/com/avengers/yoribogo/recipe/controller/RecommendedMenuController.java, server/src/main/java/com/avengers/yoribogo/recipe/service/RecommendedMenuService.java, server/src/main/java/com/avengers/yoribogo/recipe/service/RecommendedMenuServiceImpl.java, server/src/test/java/com/avengers/yoribogo/recipe/service/RecommendedMenuServiceTests.java
---
name: 기능 개발 이슈
about: 추천 요리 삭제 구현
title: Feat: 추천 요리 삭제 구현
---
- 
- 
- SOFT DELETE
```Java
// 추천 요리 삭제
@Override
public void removeRecommendedMenu(Long recommendedMenuId) {
// 기존 엔티티 조회
RecommendedMenu recommendedMenu = recommendedMenuRepository.findById(recommendedMenuId)
.orElseThrow(() -> new CommonException(ErrorCode.NOT_FOUND_RECOMMENDED_MENU));
// 이미 삭제 처리된 엔티티인 경우 예외 처리
if(recommendedMenu.getRecommendedMenuStatus() == RecommendedMenuStatus.INACTIVE) {
throw new CommonException(ErrorCode.NOT_FOUND_RECOMMENDED_MENU);
}
// INACTIVE 처리(SOFT DELETE)
recommendedMenu.setRecommendedMenuStatus(RecommendedMenuStatus.INACTIVE);
// 변경 사항 저장
recommendedMenuRepository.save(recommendedMenu);
}
```
```Java
@DisplayName("추천 요리 삭제 테스트")
@Test
void …
```
=> Feat: 추천 요리 삭제 구현

server/src/main/java/com/avengers/yoribogo/choice/controller/ChoiceController.java, server/src/main/java/com/avengers/yoribogo/choice/domain/Choice.java, server/src/main/java/com/avengers/yoribogo/choice/dto/ChoiceDTO.java, server/src/main/java/com/avengers/yoribogo/choice/repository/ChoiceRepository.java, server/src/main/java/com/avengers/yoribogo/choice/service/ChoiceService.java, server/src/main/java/com/avengers/yoribogo/choice/service/ChoiceServiceImpl.java, server/src/main/java/com/avengers/yoribogo/inquiry/domain/Answer.java, server/src/main/java/com/avengers/yoribogo/inquiry/domain/Inquiry.java, server/src/main/java/com/avengers/yoribogo/mainquestion/controller/MainQuestionController.java, server/src/main/java/com/avengers/yoribogo/mainquestion/domain/Choice.java, server/src/main/java/com/avengers/yoribogo/mainquestion/domain/MainQuestion.java, server/src/main/java/com/avengers/yoribogo/mainquestion/dto/MainQuestionDTO.java, server/src/main/java/com/avengers/yoribogo/mainquestion/repository/MainQuestionRepository.java, server/src/main/java/com/avengers/yoribogo/mainquestion/service/MainQuestionService.java, server/src/main/java/com/avengers/yoribogo/mainquestion/service/MainQuestionServiceImpl.java
---
name: 질문, 선택지 구현
about: 질문 생성/수정/삭제, 선택지 생성/수정/삭제
title: 질문 생성/수정/삭제, 질문에 포함될 선택지 생성/수정/삭제 구현
assignees: @iwillbfine 
---
---
close #43 #43
=> 질문, 선택지 구현

client/src/assets/main.css, client/src/components/HomeButton.vue, client/src/components/MainNav.vue, client/src/components/ResultNav.vue, client/src/router/router.js, client/src/views/HomeView.vue, client/src/views/WikiView.vue
---
name: 기능 개발 이슈
about: 홈버튼 컴포넌트 추가
title: Feat: 홈버튼 컴포넌트 추가
---
- 
- 
홈 버튼 컴포넌트
```Javascript
<template>
<button class="home-btn" @click="goHome">
<i class="fa-solid fa-house"></i>
</button>
</template>
<script setup>
import { useRouter } from 'vue-router'
const router = useRouter()
const goHome = () => {
router.push('/');
}
</script>
<style scoped>
.home-btn {
display: flex;
justify-content: center;
align-items: center;
width: 6.3rem;
height: 6.3rem;
border: none;
border-radius: 50%;
box-shadow: 0rem 0.35rem 0.35rem 0rem rgba(60,60,60,0.5);
cursor: pointer;
}
.home-btn i {
font-size: 3rem;
}
.home-btn:hover {
transition: 0.3s ease;
box-shadow: 0rem 0.4rem 0.4rem 0.1rem rgba(60,60,60,0.5);
}
</style>
```
사용 예시
```Javascript
<template>
<div …
```
=> Feat: 홈버튼 컴포넌트 추가

server/src/main/java/com/avengers/yoribogo/recipeboard/controller/RecipeBoardController.java, server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardService.java, server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardServiceImpl.java
---
name: #60 
about: 나만의 레시피 전체 조회, 단건 조회 구현하였습니다.
title: ''
assignees: ''
---
- 
- 
- 전체 조회 시 페이지네이션 처리
- 단건 조회시 PathVariable로 요청
```Java
```
```Javascript
```
- 
close #60
=> feat: 나만의 레시피 조회

server/src/main/java/com/avengers/yoribogo/recipeboard/controller/RecipeBoardController.java, server/src/main/java/com/avengers/yoribogo/recipeboard/controller/RecipeBoardManualController.java, server/src/main/java/com/avengers/yoribogo/recipeboard/domain/RecipeBoard.java, server/src/main/java/com/avengers/yoribogo/recipeboard/domain/RecipeBoardManual.java, server/src/main/java/com/avengers/yoribogo/recipeboard/domain/RecipeBoardStatus.java, server/src/main/java/com/avengers/yoribogo/recipeboard/dto/RecipeBoardDTO.java, server/src/main/java/com/avengers/yoribogo/recipeboard/dto/RecipeBoardManualDTO.java, server/src/main/java/com/avengers/yoribogo/recipeboard/repository/RecipeBoardManualRepository.java, server/src/main/java/com/avengers/yoribogo/recipeboard/repository/RecipeBoardRepository.java, server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardManualService.java, server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardManualServiceImpl.java, server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardService.java, server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardServiceImpl.java
---
name: 기능 개발 이슈
title: ''
assignees: ''
---
- 
- 
- 
```Java
```
```Javascript
```
- 
close #
=> Docs: 패키지 이름 수정

server/src/main/java/com/avengers/yoribogo/inquiry/service/InquiryServiceImpl.java
---
name: 기능 개발 이슈
title: ''
assignees: ''
---
- 
- 
- 
```Java
```
```Javascript
```
- 
close #
=> Docs: 오타 수정

client/src/components/HomeButton.vue, client/src/components/HomeNav.vue, client/src/components/MenuItem.vue, client/src/components/ResultBoard.vue, client/src/views/WikiView.vue
---
name: 기능 개발 이슈
about: 이미지 로딩 최적화
title: Refactor: 이미지 로딩 최적화
---
- 이미지 로딩이 느려 사용자 경험이 안 좋음
- 이미지가 로딩되는 동안 기본(Default) 이미지를 보여줌
- v-if가 아닌 v-show로 display만 바꿔 리렌더링 방지
MenuItem.vue
```Javascript
<template>
<div class="menu-item">
<div class="menu-img-wrapper">
<img
v-show="!isLoading"
:src="menuImageSrc"
alt="MenuImage"
:class="imgClass"
@load="handleImageLoad"
@error="handleImageError"
/>
</div>
<div class="menu-name-wrapper">
<span class="menu-name">{{ formattedMenuName }}</span>
</div>
</div>
</template>
<script setup>
import { ref, computed } from 'vue'
const props = defineProps({
menuImage: {
type: String,
required: true,
default: ''
},
menuName: {
type: String,
required: true
}
})
const defaultImage = ref( …
```
=> Refactor: 이미지 로딩 최적화

client/index.html, client/src/assets/main.css, client/src/components/HomeNav.vue, client/src/components/MenuItem.vue, client/src/components/PaginationComponent.vue, client/src/components/ProfileButton.vue, client/src/components/SearchBar.vue, client/src/views/MyPageView.vue, client/src/views/QuestionView.vue, client/src/views/RecipeBoardView.vue, client/src/views/ResultView.vue, client/src/views/WikiView.vue
---
name: 기능 개발 이슈
about: 프로필 버튼 구현
title: Feat: 프로필 버튼 구현
assignees: ''
---
- 
- 
- 나중에 프로필 설정하는 곳에서 이미지 사이즈를 제한하는게 좋을것 같음
ProfileButton.vue
```Javascript
<template>
<button class="profile-btn">
<img
src="https://cdxarchivephoto.s3.ap-northeast-2.amazonaws.com/1720072494119_21792adc-7e3e-4d3e-8e69-3b55fa58615c_IMG_2316.jpeg"
alt="Profile"
/>
</button>
</template>
<script setup></script>
<style scoped>
.profile-btn {
display: flex;
justify-content: center;
align-items: center;
width: 6.3rem;
height: 6.3rem;
border: none;
border-radius: 50%;
overflow: hidden;
background-color: var(--light-yellow-color);
box-shadow: 0rem 0.35rem 0.35rem 0rem rgba(60, 60, 60, 0.5);
cursor: pointer;
z-index: 9999;
}
.profile-btn img {
height: 100%;
width: 100%;
object-fit: cover;
} …
```
=> Feat: 프로필 버튼 구현

server/src/main/java/com/avengers/yoribogo/answer/service/AnswerServiceImpl.java, server/src/main/java/com/avengers/yoribogo/inquiry/domain/Inquiry.java, server/src/main/java/com/avengers/yoribogo/inquiry/dto/InquiryDTO.java, server/src/main/java/com/avengers/yoribogo/inquiry/dto/InquiryOnlyDTO.java, server/src/main/java/com/avengers/yoribogo/inquiry/repository/InquiryRepository.java, server/src/main/java/com/avengers/yoribogo/inquiry/service/InquiryService.java, server/src/main/java/com/avengers/yoribogo/inquiry/service/InquiryServiceImpl.java, server/src/main/java/com/avengers/yoribogo/mainquestion/domain/MainQuestion.java, server/src/main/java/com/avengers/yoribogo/mainquestion/dto/MainQuestionDTO.java, server/src/test/java/com/avengers/yoribogo/answer/AnswerTests.java, server/src/test/java/com/avengers/yoribogo/choice/ChoiceTests.java, server/src/test/java/com/avengers/yoribogo/inquiry/InquiryTests.java, server/src/test/java/com/avengers/yoribogo/mainquestion/MainQuestionTests.java
---
name: 테스트 코드 추가
about: main_question, choice, inquiry, answer 테스트 코드 추가
title: 테스트 코드 추가
assignees: @iwillbfine 
---
=> Test: 테스트 코드 추가

.idea/.gitignore, .idea/Yoribogo.iml, .idea/compiler.xml, .idea/dataSources.xml, .idea/gradle.xml, .idea/inspectionProfiles/Project_Default.xml, .idea/jarRepositories.xml, .idea/misc.xml, .idea/modules.xml, .idea/sqldialects.xml, .idea/uiDesigner.xml, .idea/vcs.xml, db_queries/.project, server/src/main/java/com/avengers/yoribogo/recipeboard/controller/RecipeBoardCommentController.java, server/src/main/java/com/avengers/yoribogo/recipeboard/controller/RecipeBoardReCommentController.java, server/src/main/java/com/avengers/yoribogo/recipeboard/domain/RecipeBoardComment.java, server/src/main/java/com/avengers/yoribogo/recipeboard/domain/RecipeBoardCommentStatus.java, server/src/main/java/com/avengers/yoribogo/recipeboard/domain/RecipeBoardReComment.java, server/src/main/java/com/avengers/yoribogo/recipeboard/domain/RecipeBoardReCommentStatus.java, server/src/main/java/com/avengers/yoribogo/recipeboard/dto/RecipeBoardCommentDTO.java, server/src/main/java/com/avengers/yoribogo/recipeboard/dto/RecipeBoardReCommentDTO.java, server/src/main/java/com/avengers/yoribogo/recipeboard/repository/RecipeBoardCommentRepository.java, server/src/main/java/com/avengers/yoribogo/recipeboard/repository/RecipeBoardReCommentRepository.java, server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardCommentService.java, server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardCommentServiceImpl.java, server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardReCommentService.java
---
name: 나만의 레시피 댓글 기능
about: 댓글 등록, 댓글 삭제, 댓글 수정, 댓글 회원별 조회, 댓글 게시글별 조회 기능 
title: #Feat: 나만의 레시피 댓글 기능
assignees: yncayn
---
```Java
@Override
@Transactional
public RecipeBoardCommentDTO createComment(RecipeBoardCommentDTO commentDTO) {
RecipeBoardComment comment = modelMapper.map(commentDTO, RecipeBoardComment.class);
// 기본 status -> ACTIVE 설정
comment.setRecipeBoardCommentStatus(RecipeBoardCommentStatus.ACTIVE);
// 시간 설정
comment.setRecipeBoardCommentCreatedAt(LocalDateTime.now());
if (comment.getRecipeBoardCommentContent() == null || comment.getRecipeBoardCommentContent().trim().isEmpty()) {
throw new IllegalArgumentException("댓글을 입력해주세요.");
}
try {
RecipeBoardComment createdComment = commentRepository.save(comment);
return modelMapper.map(createdComment, …
```
=> Feat:나만의레시피 댓글 기능

client/src/components/PaginationComponent.vue, client/src/views/WikiView.vue
---
name: 기능 개발 이슈
title: ''
assignees: ''
---
- falsy한 값이 넘어가면 NaN으로 나오던 버그 수정
```Javascript
// 페이지 계산을 위한 유효성 검사
const totalPages = computed(() => {
return props.data.totalPages > 0 ? props.data.totalPages : 1 // 최소 1 페이지로 설정
})
const currentPage = computed(() => {
return props.data.number >= 0 ? props.data.number + 1 : 1 // 현재 페이지 (0부터 시작하므로 +1)
})
```
- 
close #
=> Fix: 페이지네이션 오류 수정

server/src/main/java/com/avengers/yoribogo/recipeboard/controller/RecipeBoardController.java, server/src/main/java/com/avengers/yoribogo/recipeboard/repository/RecipeBoardRepository.java, server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardService.java, server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardServiceImpl.java
---
name: #92 
about: 나만의 레시피 삭제하는 기능 추가
title: ''
assignees: ''
---
- 
- 
- 삭제하는 기능 추가하였습니다.
- 이름으로 검색하는 기능 추가하였습니다.
```Java
```
```Javascript
```
- 
close #92
=> Feat: 나만의 레시피 삭제

client/src/assets/main.css, client/src/views/HomeView.vue, client/src/views/ResultView.vue, client/src/views/WikiDetailView.vue, server/src/main/java/com/avengers/yoribogo/recipe/service/AIRecipeServiceImpl.java, server/src/main/java/com/avengers/yoribogo/recipe/service/PublicDataRecipeServiceImpl.java
---
name: 기능 수정 이슈
about: 레시피 매핑 로직 수정
title: Refactor: 레시피 매핑 로직 수정
---
- modelMapper가 매핑을 못하는 경우가 있음
직접 매핑으로 수정
```Java
// AI 요리 레시피 요리 이름으로 조회(이름이 동일한 요리)
@Override
public AIRecipeDTO findAIRecipeByMenuName(String aiAnswer) {
AIRecipe aiRecipe = aiRecipeRepository.findByAiMenuName(aiAnswer).orElse(null);
if (aiRecipe == null) return null;
return AIRecipeDTO
.builder()
.aiRecipeId(aiRecipe.getAiRecipeId())
.menuName(aiRecipe.getAiMenuName())
.menuIngredient(aiRecipe.getAiMenuIngredient())
.recipeId(aiRecipe.getRecipeId())
.build();
}
```
원래는 매핑이 안되어서 요리 이름이 안 나왔음
- 
close #98
=> Fix: 추천 요리 이름 안나오는 버그 해결

client/src/assets/main.css, client/src/components/recipe/MenuItem.vue, client/src/components/recipe/RecipeManual.vue, client/src/views/MyPageView.vue, client/src/views/WikiDetailView.vue
---
name: 버그 픽스 이슈
about:  import 오류 수정
title: Fix: import 오류 수정
labels: bug
---
- [] 기능 수정
- import 매핑 잘못되어있었음
MyPageView.vue
```js
<script setup>
import HomeButton from '@/components/common/HomeButton.vue'
import MainBoard from '@/components/common/MainBoard.vue'
import ProfileButton from '@/components/common/ProfileButton.vue'
</script>
```
- 
close #
=> Fix: import 오류 수정

client/src/components/recommend/ResultBoard.vue, server/src/main/java/com/avengers/yoribogo/recipe/repository/RecipeRepository.java, server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java
---
name: 기능 개발 이슈
about: 요리 추천하기 로직 개선
title: Perf: 요리 추천하기 로직 개선
---
- 
- 
```Java
// 요리 추천하기
@Override
@Transactional
public BaseRecipeDTO registRecommendRecipe(RequestRecommendDTO requestRecommendDTO) {
// 1단계: AI에게 추천하는 요리 이름 물어보기
String prompt = "다음 정보를 바탕으로 알맞은 요리를 하나만 추천해줘: " +
"'오늘의 날씨는 어떤가요?' → '" + requestRecommendDTO.getFirst() + "', " +
"'오늘의 기분은 어떤가요?' → '" + requestRecommendDTO.getSecond() + "', " +
"'몇 명이 먹는 음식인가요?' → '" + requestRecommendDTO.getThird() + "', " +
"'채식 또는 비건 식단을 따르시나요?' → '" + requestRecommendDTO.getFourth() + "', " +
"'제가 또 알아야 하는게 있나요?' → '" + requestRecommendDTO.getFifth() + "'." +
" 특히 '" + requestRecommendDTO.getFifth() + "'를 가장 중요하게 고려하고, " +
"요리 이름은 특수문자와 다른 말은 빼고 오직 이름만 알려줘.";
String aiAnswerMenu = …
```
=> Perf: 요리 추천하기 로직 개선

server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java
---
name: 버그 수정 이슈
about: 추천 로직 버그 수정
title: Fix: 추천 로직 버그 수정
assignees: ''
---
- 같은 이름의 요리가 여러번 생성되는 버그
```Java
// 요리 추천하기
@Override
@Transactional
public BaseRecipeDTO registRecommendRecipe(RequestRecommendDTO requestRecommendDTO) {
// 1단계: AI에게 추천하는 요리 이름 물어보기
String prompt = "다음 정보를 바탕으로 알맞은 요리를 하나만 추천해줘: " +
"'오늘의 날씨는 어떤가요?' → '" + requestRecommendDTO.getFirst() + "', " +
"'오늘의 기분은 어떤가요?' → '" + requestRecommendDTO.getSecond() + "', " +
"'몇 명이 먹는 음식인가요?' → '" + requestRecommendDTO.getThird() + "', " +
"'채식 또는 비건 식단을 따르시나요?' → '" + requestRecommendDTO.getFourth() + "', " +
"'제가 또 알아야 하는게 있나요?' → '" + requestRecommendDTO.getFifth() + "'." +
" 특히 '" + requestRecommendDTO.getFifth() + "'를 가장 중요하게 고려하고, " +
"요리 이름은 특수문자와 다른 말은 빼고 오직 이름만 알려줘.";
String aiAnswerMenu = …
```
=> Fix: 추천 로직 버그 수정

server/src/main/java/com/avengers/yoribogo/user/controller/UserController.java, server/src/main/java/com/avengers/yoribogo/user/service/UserService.java
---
name: 회원탈퇴 및 재활성화 API 추가
about: 회원탈퇴 및 재활성화 API 추가
---
```Java
/**
* 사용자 계정을 비활성화하는 메서드.
*/
public UserEntity deactivateUser(Long userId) {
// Optional 처리 및 예외 발생
UserEntity userEntity = userRepository.findById(userId)
.orElseThrow(() -> new CommonException(ErrorCode.NOT_FOUND_USER));
// 사용자 상태를 비활성화(INACTIVE)로 변경
userEntity.deactivateUser();
// 변경된 상태를 저장하고 반환
return userRepository.save(userEntity);
}
/**
* 사용자 계정을 활성화하는 메서드.
*/
public UserEntity activateUser(String userAuthId) {
// Optional 처리 및 예외 발생
UserEntity userEntity = userRepository.findByUserIdentifier("NORMAL_" + userAuthId)
.orElseThrow(() -> new CommonException(ErrorCode.NOT_FOUND_USER));
// 사용자 상태를 활성화(ACTIVE)로 변경
userEntity.activateUser();
// 변경된 상태를 저장하고 반환
return …
```
=> 회원탈퇴 및 재활성화 API 추가

server/src/main/java/com/avengers/yoribogo/user/controller/UserController.java, server/src/main/java/com/avengers/yoribogo/user/domain/vo/password/RequestUpdateLoggedInPasswordVO.java, server/src/main/java/com/avengers/yoribogo/user/domain/vo/password/RequestUpdatePasswordUserVO.java, server/src/main/java/com/avengers/yoribogo/user/service/UserService.java
---
name:  비밀번호 찾기, 비밀번호 재설정 api 추가
about: 비밀번호 찾기는 로그인전에 사용하고, 비밀번호 재설정은 로그인한 사용자가 재설정하는 기능입니다.
---
```Java
// 설명. 로그인 전 사용자 비밀번호 재설정
public UserEntity updatePassword(String userAuthId, String newPassword) {
// 1. 사용자 ID를 통해 사용자를 조회
UserEntity userEntity = userRepository.findByUserIdentifier("NORMAL_" + userAuthId)
.orElseThrow(() -> new CommonException(ErrorCode.NOT_FOUND_USER));
// 2. 비번 재설정시 이메일 인증여부 확인
if (userEntity.getEmail() != null && !userEntity.getEmail().isEmpty()) {
String emailVerificationStatus = stringRedisTemplate.opsForValue().get(userEntity.getEmail());
if (!"True".equals(emailVerificationStatus)) {
log.error("이메일 인증이 완료되지 않았습니다: {}", userEntity.getEmail());
throw new CommonException(ErrorCode.EMAIL_VERIFICATION_REQUIRED); // 이메일 인증이 …
```
=> Feat: 비밀번호 찾기, 비밀번호 재설정 api 추가

client/src/components/common/NotificationButton.vue, client/src/views/MyPageView.vue, client/src/views/QnAview.vue, client/src/views/RecipeBoardView.vue, client/src/views/WikiView.vue
---
name: 기능 개발 이슈
title: ''
assignees: ''
---
- 
- 
```js
<template>
<div class="notification-btn">
<div class="notification-icon-wrapper" @click="toggleMenu">
<i class="fa-solid fa-bell"></i>
</div>
<ul class="notification-list" v-show="isMenuVisible">
<li class="notification" @click="goMyPage">
<span>알림: 회원가입을 축하합니다!</span>
</li>
<li class="notification">
<span>알림: 요리보고에 오신것을 환영합니다~~</span>
</li>
<li class="notification">
<span>알림: 요리보고에 오신것을 환영합니다~~</span>
</li>
<li class="notification">
<span>알림: 요리보고에 오신것을 환영합니다~~</span>
</li>
</ul>
</div>
</template>
<script setup>
import { ref } from 'vue'
const isMenuVisible = ref(false)
const toggleMenu = () => {
isMenuVisible.value = !isMenuVisible.value
}
</script>
<style scoped>
.notification-btn { …
```
=> Feat: 알림 버튼 구현

server/src/main/java/com/avengers/yoribogo/user/controller/UserController.java, server/src/main/java/com/avengers/yoribogo/user/dto/profile/RequestUpdateUserDTO.java, server/src/main/java/com/avengers/yoribogo/user/service/UserService.java
---
name: 사용자 프로필 수정 api 추가
about: 사용자 프로필(닉네임, 프로필 사진) 수정
---
```Java
/**설명.
*  사용자의 프로필(닉네임, 이미지)을 업데이트하는 메서드.
*설명.
* @param userId 프로필을 업데이트할 사용자의 ID
* @param userUpdateDTO 업데이트할 정보가 담긴 DTO 객체
* @return 업데이트된 UserEntity 객체
* @throws CommonException 사용자가 존재하지 않을 경우 발생
*/
public UserEntity updateProfile(Long userId, RequestUpdateUserDTO userUpdateDTO) {
Optional<UserEntity> user = userRepository.findById(userId);
if (user.isEmpty()) {
throw new CommonException(ErrorCode.NOT_FOUND_USER);
}
UserEntity userEntity = user.get();
String imageUrl = null;
// 닉네임 중복 검증(null이 아니고 기존과 같지 않은 경우에)
if (userUpdateDTO.getNickname() != null ) {
if (userUpdateDTO.getNickname().equals(userEntity.getNickname()))
{
throw new CommonException(ErrorCode.DUPLICATE_NICKNAME); …
```
=> Feat: 사용자 프로필 수정 api 추가

server/src/main/java/com/avengers/yoribogo/recipeboard/controller/RecipeBoardController.java, server/src/main/java/com/avengers/yoribogo/recipeboard/controller/RecipeBoardFavoriteController.java, server/src/main/java/com/avengers/yoribogo/recipeboard/domain/RecipeBoard.java, server/src/main/java/com/avengers/yoribogo/recipeboard/domain/RecipeBoardFavorite.java, server/src/main/java/com/avengers/yoribogo/recipeboard/dto/MyFavoriteBoardDTO.java, server/src/main/java/com/avengers/yoribogo/recipeboard/dto/RecipeBoardFavoriteDTO.java, server/src/main/java/com/avengers/yoribogo/recipeboard/dto/ResponseBoardDTO.java, server/src/main/java/com/avengers/yoribogo/recipeboard/dto/ResponseFavoriteDTO.java, server/src/main/java/com/avengers/yoribogo/recipeboard/repository/RecipeBoardFavoriteRepository.java, server/src/main/java/com/avengers/yoribogo/recipeboard/repository/RecipeBoardRepository.java, server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardFavoriteService.java, server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardFavoriteServiceImpl.java, server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardService.java, server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardServiceImpl.java
---
name: #100 
about: 즐겨찾기 등록, 취소, 회원별 조회 기능 구현하였습니다.
title: ''
assignees: ''
---
- 
- 
- RESTful 하게 다 나눴습니다.
```Java
```
```Javascript
```
- 
close #
=> Feat: 나만의 레시피 즐겨찾기 기능

db_queries/integrated_data_insert.sql, server/src/main/java/com/avengers/yoribogo/user/controller/UserController.java, server/src/main/java/com/avengers/yoribogo/user/domain/Tier.java, server/src/main/java/com/avengers/yoribogo/user/domain/UserEntity.java, server/src/main/java/com/avengers/yoribogo/user/dto/profile/ResponseUserProfileDTO.java, server/src/main/java/com/avengers/yoribogo/user/repository/TierRepository.java, server/src/main/java/com/avengers/yoribogo/user/repository/UserRepository.java, server/src/main/java/com/avengers/yoribogo/user/service/OAuth2LoginService.java, server/src/main/java/com/avengers/yoribogo/user/service/UserService.java, server/src/test/java/com/avengers/yoribogo/user/service/UserServiceTest.java
---
name: UserEntity와 Tier 테이블 연관관계 매핑
---
```Java
@ManyToOne
@JoinColumn(name = "tier_id", referencedColumnName = "tier_id")
private Tier tier;
```
=> Refactor: UserEntity와 Tier 테이블 연관관계 매핑

client/src/assets/main.css, client/src/views/HomeView.vue, client/src/views/ResultView.vue, server/src/main/java/com/avengers/yoribogo/openai/service/OpenAIServiceImpl.java, server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java
---
name: 기능 개발 이슈
about: 만족도 조사 구현
title: Feat: 만족도 조사 구현
---
- 
- 
```Js
<template>
<div class="response-board">
<div class="good" @click="handleClickGood">
<i class="fa-solid fa-face-smile"></i>
<div class="text-wrapper">
<span>만족했어요</span>
</div>
</div>
<div class="bad" @click="handleClickBad">
<div class="text-wrapper">
<span>별로예요</span>
</div>
<i class="fa-solid fa-face-frown"></i>
</div>
</div>
</template>
<script setup>
const emit = defineEmits(['good', 'bad'])
const handleClickGood = () => {
emit('good')
}
const handleClickBad = () => {
emit('bad')
}
</script>
<style scoped>
.response-board {
display: flex;
justify-content: center;
align-items: center;
gap: 0.5rem;
padding: 0.5rem;
border-radius: 5rem;
background-color: …
```
=> Feat: 만족도 조사 구현

client/src/components/recommend/ResponseBoard.vue
=> Add: 컴포넌트 추가

server/src/main/java/com/avengers/yoribogo/recipeboard/controller/RecipeBoardController.java, server/src/main/java/com/avengers/yoribogo/recipeboard/dto/RecipeBoardDTO.java, server/src/main/java/com/avengers/yoribogo/recipeboard/dto/RecipeBoardManualDTO.java, server/src/main/java/com/avengers/yoribogo/recipeboard/repository/RecipeBoardManualRepository.java, server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardService.java, server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardServiceImpl.java
---
name: 기능 개발 이슈
about: 나만의 레시피 관련 이미지를 s3 업로드 용으로 리팩터
title: ''
assignees: ''
---
- 
- 
- 
```Java
```
```Javascript
```
- 
close #
=> Refactor: 나만의 레시피 s3 업로드 관련 리팩터 및 로직 수정

server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java
---
name: 기능 개발 이슈
about: 프롬프트 개선
title: Perf: 프롬프트 개선
---
- 
- 
```java
// 요리 추천하기
@Override
@Transactional
public BaseRecipeDTO registRecommendRecipe(RequestRecommendDTO requestRecommendDTO) {
// 1단계: AI에게 추천하는 요리 이름 물어보기
String prompt = "날씨: '" + requestRecommendDTO.getFirst() + "', 기분: '" + requestRecommendDTO.getSecond() +
"', 인원: '" + requestRecommendDTO.getThird() + "', 채식 여부: '" + requestRecommendDTO.getFourth() +
"', 추가 사항: '" + requestRecommendDTO.getFifth() + "'. " +
"앞의 정보를 바탕으로, 추가 사항이 있으면 그 요청을 우선 고려하고, 없으면 다양한 나라의 요리 중 한 가지를 " +
"'요리이름(Detailed english description of the dish)' 형식으로 한 문장으로 추천해줘.";
String aiAnswerMenu = openAIService.getRecommend(prompt).getChoices().get(0).getMessage().getContent();
System.out.println(aiAnswerMenu); …
```
=> Perf: 프롬프트 개선

client/src/api/axios.js, client/src/api/user.js, client/src/components/common/YesNoButton.vue, client/src/components/user/login/FindIdStep1.vue, client/src/components/user/login/FindIdStep2.vue, server/src/main/java/com/avengers/yoribogo/user/controller/UserController.java, server/src/main/java/com/avengers/yoribogo/user/domain/vo/UserIdEmailVerificationVO.java, server/src/main/java/com/avengers/yoribogo/user/service/EmailVerificationService.java
---
name: 아이디 찾기 세부창 
about: 아이디 찾기는 닉네임, 이메일 인증을 통해 가능하다.
assignees: ''
---
```Javascript
// 인증번호 확인 및 사용자 정보 조회 API 호출 함수
const confirmVerificationCode = async () => {
try {
// 새로운 사용자 인증 및 정보 조회 API 호출
const response = await verifyUserNicknameCode(nickname.value, email.value, verificationCode.value);
if (response.success) {
verificationMessage.value = '인증되었습니다.';
verificationError.value = '';
isVerified.value = true;
userAuthId.value = response.data.userAuthId; // 사용자 ID 설정
nickname.value = response.data.nickname; // 사용자 닉네임 설정
} else {
verificationError.value = response.message || '인증번호가 올바르지 않습니다.';
verificationMessage.value = '';
}
} catch (error) {
verificationError.value = error.response?.data?.message || '인증에 실패했습니다. 다시 시도해주세요.';
verificationMessage.value = …
```
=> 아이디 찾기 세부창 

client/src/api/user.js, client/src/components/user/login/AccountReactivationModal.vue, client/src/components/user/login/FindIdStep1.vue, client/src/components/user/login/PasswordResetStep1.vue, client/src/components/user/login/PasswordResetStep2.vue, client/src/views/user/LoginView.vue, server/src/main/java/com/avengers/yoribogo/user/service/UserService.java
---
name: 비밀번호 찾기 세부창 추가
about: 비밀번호 찾기 세부창은 아이디와 이메일을 입력해서 찾을 수 있다.
---
```Javascript
// 인증번호 발송 API 호출 함수 (비밀번호 찾기)
const sendVerificationCode = async () => {
try {
// user.js에 정의된 sendPasswordResetVerificationEmail 함수를 사용하여 API 호출
const response = await sendPasswordResetVerificationEmail(
props.passwordResetData.user_auth_id,  // 아이디 및 이메일 발송
props.passwordResetData.email
);
if (response.success) {
verificationMessage.value = '인증번호가 이메일로 발송되었습니다.';
verificationError.value = '';
} else {
verificationError.value = response.error.message || '인증번호 발송에 실패했습니다.';
verificationMessage.value = '';
}
} catch (error) {
verificationError.value = error.response?.data?.message || '서버 오류로 인해 인증번호 발송에 실패했습니다.';
verificationMessage.value = '';
}
};
// 발송 버튼 클릭 시 호출 …
```
=> 비밀번호 찾기 세부창, 재활성화 기능 추가

client/src/components/recommend/ResultBoard.vue
---
name: 기능 개발 이슈
about: 메뉴 이름 나오는 길이 수정
title: Refactor: 메뉴 이름 나오는 길이 수정
assignees: ''
---
- 
- 
- 메뉴 이름이 너무 길면 UI 깨지는 경우가 있어 수정
- 
close #
=> Refactor: 메뉴 이름 나오는 길이 수정

client/src/api/user.js, client/src/components/user/profile/UserProfile.vue, client/src/views/MyPageView.vue, server/src/main/java/com/avengers/yoribogo/user/controller/UserController.java, server/src/main/java/com/avengers/yoribogo/user/dto/profile/ResponseUserProfileDTO.java
---
name: 마이페이지에 프로필 사진 추가
---
```Javascript
<template>
<div class="mypage-view">
<header>
<NotificationButton class="notification-btn"></NotificationButton>
<ProfileButton class="profile-btn"></ProfileButton>
<HomeButton class="home-btn"></HomeButton>
</header>
<MainBoard :cur="'mypage'">
<div class="user-profile-section">
<UserProfile :userProfile="userProfile" @editProfile="openEditProfileModal" />
</div>
</MainBoard>
</div>
</template>
<script setup>
import HomeButton from '@/components/common/HomeButton.vue';
import MainBoard from '@/components/common/MainBoard.vue';
import ProfileButton from '@/components/common/ProfileButton.vue';
import NotificationButton from '@/components/common/NotificationButton.vue';
import …
```
=> Feat: 마이페이지에 프로필 사진 추가

client/src/components/mypage/BookmarkedRecipes.vue, client/src/components/mypage/MyRecipes.vue, client/src/components/mypage/SatisfiedRecipes.vue, client/src/components/user/profile/ProfileEditModal.vue, client/src/components/user/profile/UserProfile.vue, client/src/views/MyPageView.vue
---
name: 마이페이지 틀 세팅 완료
---
==
=> Feat: 마이페이지 틀 세팅 완료

client/src/views/QnAview.vue, client/src/views/QnaDetailView.vue
---
name: 문의 게시판 글씨 크기 수정, 답변 삭제 버튼 수정
about: 문의 게시판 글씨 크기 수정, 답변 삭제 버튼 수정
title: 문의 게시판 글씨 크기 수정, 답변 삭제 버튼 수정
assignees: ''
---
=> Fix: 문의 게시판 글씨 크기 수정, 답변 삭제 버튼 수정

client/src/components/user/profile/AccountDeactivationModal.vue, client/src/components/user/profile/AccountOptionsModal.vue, client/src/components/user/profile/ProfileEditModal.vue, client/src/components/user/signup/SignupStep1.vue, client/src/views/MyPageView.vue
---
name:  사용자 프로필 정보 세부창 및 회원 탈퇴 세부
title: '사용자 프로필 정보 세부창 및 회원 탈퇴 세부창 추가'
---
```Javascript
// 프로필 업데이트 함수
const completeUpdateProfile = async () => {
if (!canComplete.value) return;
try {
// FormData 객체 생성 (이미 user.js에 정의된 updateUserProfile 함수는 이미 formData를 사용하므로 따로 만들 필요 없음)
const profileImage = profilePicture.value || null; // 이미지가 없을 경우 null 처리
console.log("userId:", tokenStore.token.userId);
console.log("accessToken:", tokenStore.token.accessToken); // accessToken 값을 출력하여 확인
// updateUserProfile 함수를 호출
const response = await updateUserProfile(tokenStore.token.userId, nickname.value, profileImage, tokenStore.token.accessToken);
if (response.success) {
alert('프로필이 성공적으로 업데이트되었습니다!');
closeModal();
router.push('/mypage'); // 마이페이지로 이동
} else { …
```
=> Feat: 사용자 프로필 정보 세부창 및 회원 탈퇴 세부창 추가

client/src/components/user/profile/AccountOptionsModal.vue, client/src/components/user/profile/UserProfile.vue, client/src/components/user/sns/KakaoCallback.vue, client/src/components/user/sns/NaverCallback.vue, client/src/components/user/sns/ProfileOAuthModal.vue
---
name: 카카오 로그인, 네이버 로그인 완료
about: 카카오 로그인, 네이버 로그인
---
```Javascript
// 모달 닫기 함수 - 닉네임을 입력하지 않았을 경우 경고창을 표시
const closeModal = () => {
if (!nickname.value || !isNicknameAvailable.value) {
alert('닉네임을 설정하셔야 합니다!');
} else {
showProfileModal.value = false; // 모달 창 닫기
}
};
```
- 소셜 로그인은 닉네임이 설정되지않으면 기본적으로 닉네임 설정창이 뜨고, 설정하지 않으면 다른 창으로 이동하지 못한다.
=> Feat: 카카오 로그인, 네이버 로그인 완료

client/src/views/QnAview.vue
---
name: inquiry.userId -> inquiry.user.userId로 변경
about: inquiry.userId -> inquiry.user.userId로 변경
title: inquiry.userId -> inquiry.user.userId로 변경
assignees: ''
---
=> Fix: inquiry.userId -> inquiry.user.userId로 변경

client/src/views/MyPageView.vue, server/src/main/java/com/avengers/yoribogo/recipe/controller/RecommendedMenuController.java, server/src/main/java/com/avengers/yoribogo/recipe/repository/RecommendedMenuRepository.java, server/src/main/java/com/avengers/yoribogo/recipe/service/RecommendedMenuService.java, server/src/main/java/com/avengers/yoribogo/recipe/service/RecommendedMenuServiceImpl.java, server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardFavoriteServiceImpl.java, server/src/main/java/com/avengers/yoribogo/recipeboard/service/RecipeBoardServiceImpl.java, server/src/test/java/com/avengers/yoribogo/recipe/service/RecommendedMenuServiceTests.java
---
name: 기능 개발 이슈
about: 만족한 요리 페이지네이션 추가
title: Refactor: 만족한 요리 페이지네이션 추가
assignees: ''
---
- 
- 
// 추천 요리 회원별 조회
@Override
public Page<GoodMenuDTO> findRecommendedMenuByUserId(Long userId, Integer pageNo) {
// 페이지 번호 유효성 검사
if (pageNo == null || pageNo < 1) {
throw new CommonException(ErrorCode.INVALID_PARAMETER_FORMAT);
}
// 페이지와 한 페이지당 요소 수 설정 (pageNumber는 0부터 시작)
Pageable pageable = PageRequest.of(
pageNo - 1,
ELEMENTS_PER_PAGE,
Sort.by(Sort.Direction.DESC, "recommendedMenuId")
);
// 기존 엔티티 목록 조회
Page<GoodMenuDTO> recommendedMenuList = recommendedMenuRepository.findRecommendedMenuWithRecipeByUserId(
userId, Satisfaction.GOOD, RecommendedMenuStatus.ACTIVE, pageable);
// 조회된 결과가 없을 때 예외 처리
if (recommendedMenuList.isEmpty()) {
throw new …
=> Refactor: 만족한 요리 페이지네이션 추가

client/src/router/router.js, client/src/views/RecipeBoardDetailView.vue, client/src/views/RecipeBoardListView.vue, server/src/main/java/com/avengers/yoribogo/recipeboard/dto/RecipeBoardDTO.java
---
name: 기능 개발 이슈
about: 전체 조회와 상세 조회 구현
title: ''
assignees: 최해관
---
- 
- 
- 
```Java
```
```Javascript
```
- 
close #
=> Feat: 나만의 레시피 게시글 전체 조회 및 상세 조회와 연결

client/src/router/router.js, client/src/views/MyPageView.vue
---
name: 기능 개발 이슈
about: 마이페이지 페이지네이션 일부구현
title: Feat: 마이페이지 페이지네이션 일부구현
---
- 
- 
- 
close #
=> Feat: 마이페이지 페이지네이션 일부구현

server/src/test/java/com/avengers/yoribogo/inquiry/InquiryTests.java
=> Fix: 테스트 코드 빌드를 위해 주석 처리

client/src/components/recipe-board/RecipeViewSwitchButton.vue, client/src/views/RecipeBoardListView.vue
---
name: 기능 개발 이슈
about: 리스트 토글 전환 기능 구현
title: ''
assignees: ''
---
- 
- 
- 
```Java
```
```Javascript
```
- 
close #
=> Feat: 나만의 레시피 주간, 전체 토글 전환

server/src/test/java/com/avengers/yoribogo/inquiry/InquiryTests.java
---
name: 문의 테스트 코드 수정
about: 문의 테스트 코드 수정
title: 문의 테스트 코드 수정
assignees: ''
---
=> Fix: 문의 테스트 코드 수정

client/src/components/common/MainBoard.vue, client/src/views/QnaDetailView.vue, client/src/views/QnaView.vue
---
name: 기능 개발 이슈
about: css 수정
title: Style: css 수정
---
- 
- 
- 
- 
close #
=> Style: css 수정

client/src/assets/main.css
---
name: 기능 개발 이슈
about: css 수정
title: Style: css 수정
assignees: @woodart8
---
- 
- 
- 
- 
close #
=> Style: HomeNav css 수정

client/src/components/recipe-board/AtrributeTextAndImageInput.vue, client/src/components/recipe-board/WriteRecipeBoardComponent.vue
---
name: 기능 개발 이슈
title: ''
assignees: ''
---
- 
- 
- 
```Java
```
```Javascript
```
- 
close #
=> Feat: 나만의 레시피 등록 중간 커밋

client/src/components/recipe-board/WriteCommentInput.vue, client/src/components/recipe-board/WriteRecommentInput.vue, client/src/router/router.js, client/src/views/RecipeBoardDetailView.vue, client/src/views/RecipeBoardListView.vue, client/src/views/RecipeBoardWriteView.vue
---
name: 기능 개발 이슈
about: 나만의 레시피 댓글 작성 구현
title: Feat: 나만의 레시피 댓글 작성 구현
---
- 
- 
```js
// 새 댓글 추가 처리 함수
const handleAddComment = async (newComment) => {
try {
const userId = JSON.parse(localStorage.getItem('token')).userId
const commentData = {
comment_content: newComment,
recipe_board_id: route.params.board_id,
user_id: userId
}
// 서버로 새 댓글 전송
const response = (
await axios.post(`/api/recipe-board/${route.params.board_id}/comments`, commentData)
).data
// 새로운 댓글을 로컬에 추가
if (response.success) {
fetchData()
}
} catch (error) {
console.error('Failed to add comment:', error)
}
}
// 댓글 작성 함수
const submitComment = () => {
if (newComment.value.trim() !== '') {
handleAddComment(newComment.value)
newComment.value = '' // 입력창 초기화
}
}
```
- 
close #
=> Feat: 나만의 레시피 댓글 작성 구현

client/src/components/recipe-board/WriteCommentInput.vue, client/src/views/RecipeBoardDetailView.vue
---
name: 기능 개발 이슈
about: 프로필 둥글게 나오게 수정
title: Refactor: 프로필 둥글게 나오게 수정
---
- 
- 
- 
close #
=> Refactor: 프로필 둥글게 나오게 수정

client/src/views/RecipeBoardListView.vue
---
name: 기능 개발 이슈
about: 검색 기능 수정
title: Fix: 검색 기능 수정
---
- 검색시 라우터 경로 오류 발생
- 
- 
close #
=> Fix: 검색 기능 수정

server/src/main/java/com/avengers/yoribogo/recipeboard/dto/RecipeBoardCommentDTO.java
---
name: 기능 개발 이슈
title: ''
assignees: ''
---
- 
- 
```java
package com.avengers.yoribogo.recipeboard.dto;
import com.avengers.yoribogo.recipeboard.domain.RecipeBoardCommentStatus;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;
import java.time.LocalDateTime;
@Data
public class RecipeBoardCommentDTO {
@JsonProperty("comment_id")
private Long recipeBoardCommentId;
@JsonProperty("comment_content")
private String recipeBoardCommentContent;
@JsonProperty("comment_created-at")
private LocalDateTime recipeBoardCommentCreatedAt;
@JsonProperty("recipe_board_id")
private Long recipeBoardId;
@JsonProperty("user_id")
private Long userId;
@JsonProperty("comment_status")
private RecipeBoardCommentStatus recipeBoardCommentStatus;
} …
```
=> Refactor: JsonProperty 수정

client/src/components/recipe-board/WriteRecipeBoardComponent.vue, client/src/router/router.js, client/src/views/RecipeBoardDetailView.vue, client/src/views/RecipeBoardListView.vue, client/src/views/RecipeBoardWriteView.vue
=> Feat: 레시피 보드에서 탭 제거

client/src/views/QuestionView.vue, client/src/views/RecipeBoardListView.vue
---
name: 기능 개발 이슈
title: ''
assignees: ''
---
- 
- 
- 
```Java
```
```Javascript
```
- 
close #
=> Refactor: 추천화면에서 알림 삭제

client/src/views/RecipeBoardDetailView.vue, client/src/views/RecipeBoardListView.vue
---
name: 기능 개발 이슈
title: ''
assignees: ''
---
- 
- 
- 
```Java
```
```Javascript
```
- 
close #
=> Feat: 나만의 레시피 페이지에 알림버튼 추가

client/src/views/WikiDetailView.vue
---
name: 기능 개발 이슈
title: ''
assignees: ''
---
- 
- 
- 
```Java
```
```Javascript
```
- 
close #
=> Feat: 요리 상세페이지 알림 버튼 추가

db_queries/table_definition.sql
---
name: 기능 개발 이슈
title: ''
assignees: ''
---
- 
- 
- 
```Java
```
```Javascript
```
- 
close #
=> Refactor: 알림 테이블 수정

client/src/components/common/ProfileButton.vue
---
name: 기능 개발 이슈
title: ''
assignees: ''
---
- 
- 
- 
```Java
```
```Javascript
```
- 
close #
=> Fix: 로그아웃 버그 수정

client/src/components/recommend/ResultBoard.vue, server/src/main/java/com/avengers/yoribogo/recipe/service/ImageService.java, server/src/main/java/com/avengers/yoribogo/recipe/service/ImageServiceImpl.java, server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeManualService.java, server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeManualServiceImpl.java, server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java
---
name: 기능 개발 이슈
about: 요리 추천 매뉴얼 생성 비동기 처리
title: Perf: 요리 추천 매뉴얼 생성 비동기 처리
---
- 
- 
비동기 처리
```java
// AI 생성 매뉴얼 등록
@Async
@Override
public void registAIRecipeManual(Long recipeId, String recipePrompt) {
String aiAnswerRecipe = openAIService.getRecommend(recipePrompt).getChoices().get(0).getMessage().getContent();
log.info(aiAnswerRecipe);
// ':'가 있는 경우, ':' 이후의 문자열만 남기기
aiAnswerRecipe = parseString(aiAnswerRecipe);
// AI가 생성한 요리 레시피 매뉴얼 등록
List<Map<String, String>> manual = new ArrayList<>();
List<String> contents = Arrays.stream(aiAnswerRecipe.split("\n")).toList();
for (String content : contents) {
Map<String, String> map = new HashMap<>();
map.put("content", content);
manual.add(map);
}
for(int i = 0; i < manual.size(); i++) {
// 매뉴얼 생성 …
```
=> Perf: 요리 추천 매뉴얼 생성 비동기 처리

client/src/views/WikiDetailView.vue, server/build.gradle, server/src/main/java/com/avengers/yoribogo/openai/dto/RequestChatDTO.java, server/src/main/java/com/avengers/yoribogo/openai/dto/ResponseChatDTO.java, server/src/main/java/com/avengers/yoribogo/openai/dto/ResponseChatFluxDTO.java, server/src/main/java/com/avengers/yoribogo/openai/provider/OpenAIProvider.java, server/src/main/java/com/avengers/yoribogo/openai/service/OpenAIService.java, server/src/main/java/com/avengers/yoribogo/openai/service/OpenAIServiceImpl.java, server/src/main/java/com/avengers/yoribogo/recipe/controller/RecipeManualController.java, server/src/main/java/com/avengers/yoribogo/recipe/dto/RequestAIRecipeManualDTO.java, server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeManualService.java, server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeManualServiceImpl.java, server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java
---
name: 기능 개발 이슈
about: 요리 추천 매뉴얼 생성 WebFlux 처리
title: Perf: 요리 추천 매뉴얼 생성 WebFlux 처리
---
- 
- 
- 비동기 처리
- 
close #
=> Perf: 요리 추천 매뉴얼 생성 WebFlux 처리

server/src/main/java/com/avengers/yoribogo/openai/dto/RequestChatFluxDTO.java, server/src/main/java/com/avengers/yoribogo/openai/dto/ResponseChatDTO.java, server/src/main/java/com/avengers/yoribogo/openai/provider/OpenAIProvider.java, server/src/main/java/com/avengers/yoribogo/openai/service/OpenAIServiceImpl.java, server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java
---
name: 기능 개발 이슈
about: 추천 오류 해결
title: Fix: 추천 오류 해결
assignees: ''
---
- : 들어간 경우 파싱하는 메소드 적용시켜서 에러 발생
- 
- 
close #
=> Fix: 추천 오류 해결

client/src/components/recommend/ResultBoard.vue, client/src/views/WikiDetailView.vue, server/src/main/java/com/avengers/yoribogo/notification/notification/service/NotificationService.java, server/src/main/java/com/avengers/yoribogo/recipe/service/ImageServiceImpl.java
---
name: 기능 개발 이슈
about: sse를 통한 요리사진 리렌더링
title: Perf: sse를 통한 요리사진 리렌더링
assignees: ''
---
- 
- 
```js
onMounted(() => {
// SSE 연결 생성
const eventSource = new EventSource('/api/notifications/sseconnect')
fetchData()
eventSource.addEventListener('image-update', (event) => {
menuImageSrc.value = event.data
console.log('사진 업데이트됨: ', event.data)
})
})
```
- 
close #
=> Perf: sse를 통한 요리사진 리렌더링

client/src/views/MyPageView.vue, client/src/views/QnaCreateView.vue, client/src/views/QnaDetailView.vue, client/src/views/QnaEditView.vue, client/src/views/QnaView.vue, client/src/views/RecipeBoardDetailView.vue, client/src/views/RecipeBoardListView.vue, client/src/views/RecipeBoardWriteView.vue, client/src/views/ResultView.vue, client/src/views/WikiDetailView.vue, client/src/views/WikiView.vue
---
name: 기능 개발 이슈
about: 정규표현식 수정
title: Refactor: 정규표현식 수정
---
- 
- 
```js
while (!done && reader) {
const { value, done: doneReading } = await reader.read()
done = doneReading
const chunkValue = decoder.decode(value)
lastMessage += chunkValue
text = lastMessage.replaceAll('data:', '').replace(/\n/g, '')
// 공백만 있을 경우
if (text.trim === '') {
lastMessage = ''
continue
}
// 문장이 문자.으로 끝날 경우
if (/[a-zA-Z가-힣]\.$/.test(text)) {
manualList.value[manualList.value.length - 1].manual_content = text.trim()
lastMessage = ''
text = ''
// 6개 이하일 때 새로운 빈 항목 추가
if (manualList.value.length < maxLength) {
manualList.value.push({ manual_content: '', manual_image: null })
}
}
// 이외의 경우 (수집 중인 문장이므로 마지막 항목 업데이트)
else {
if (manualList.value.length > 0) { …
```
=> Refactor: 정규표현식 수정

server/src/main/java/com/avengers/yoribogo/config/AsyncConfig.java, server/src/main/java/com/avengers/yoribogo/recipe/service/RecipeServiceImpl.java
---
name: 기능 개발 이슈
about: 쓰레드 수 조절
title: Refactor: 쓰레드 수 조절
---
- 
- 
- 
```java
package com.avengers.yoribogo.config;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.scheduling.annotation.EnableAsync;
import org.springframework.core.task.AsyncTaskExecutor;
import org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor;
@Configuration
@EnableAsync
public class AsyncConfig {
@Bean(name = "taskExecutor")
public AsyncTaskExecutor taskExecutor() {
ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
executor.setCorePoolSize(10); // 최소 유지 스레드 수
executor.setMaxPoolSize(50);  // 최대 스레드 수
executor.setQueueCapacity(100); // 큐 크기 …
```
=> Refactor: 쓰레드 수 조절
